sudo: required

language: perl6

perl6:
  - latest

go:
  - 1.8.x

before_install:
  - mkdir $HOME/gopath
  - wget https://storage.googleapis.com/golang/go1.8.linux-amd64.tar.gz
  - tar -xzf go1.8.linux-amd64.tar.gz
  
install:
  - rakudobrew build zef
  - $HOME/go/bin/go get github.com/bradclawsie/rscs
  
before_script:
  - zef --/test --/test-depends install HTTP::UserAgent
  - zef --/test --/test-depends install JSON::Tiny

env:
  - GOPATH=$HOME/gopath  
