sudo: required

language: perl6

perl6:
  - latest

install:
  - rakudobrew build zef
  - go get github.com/bradclawsie/rscs
  
before_script:
  - zef --/test --/test-depends install HTTP::UserAgent
  - zef --/test --/test-depends install JSON::Tiny
